trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python36Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.6'
      Python36Mac:
        imageName: 'macos-10.13'
        python.version: '3.6'
      Python37Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.7'
      Python37Mac:
        imageName: 'macos-10.13'
        python.version: '3.7'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip wheel
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python setup.py sdist
    displayName: 'Build sdist'

  - script: pip install dist/*.tar.gz
    condition: in( variables['Agent.OS'], 'Linux', 'Darwin')
    displayName: 'Install from sdist (Linux, Mac)'

  - script: pip install -e .
    condition: eq( variables['Agent.OS'], 'Windows_NT')
    displayName: 'Install with pip (Windows)'

  - script: |
      python -m pytest tests
    displayName: 'Run tests'
